// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxinqppnnptlaiqljtog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4aW5xcHBubnB0bGFpcWxqdG9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0ODY0MzUsImV4cCI6MjA1ODA2MjQzNX0.9kgoZjRPvsIraShMUpRIgfrM7Sqf1YAhBSqXejT9-I8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);